Soft delete user
tatunka/cs414-f20-TeamWeThemBoys pull request #21
Opened 2020-11-09 18:22 UTC by wstnmssr

2020-11-09 18:25 UTC, tatunka commented on xGame/Java/xgame/src/test/java/com/xgame/restservice/UserService.java
> +		userRepo.deleteById(user.getId());
surround with try catch. delete user in finally block.

2020-11-09 18:25 UTC, tatunka commented on xGame/Java/xgame/src/test/java/com/xgame/restservice/UserService.java
> +		userRepo.delete(userEntity3);
same as above

2020-11-09 18:26 UTC, tatunka commented on xGame/Java/xgame/src/test/java/com/xgame/restservice/UserService.java
> +		userRepo.deleteById(user.getId());
same as above

2020-11-09 18:26 UTC, tatunka requested changes
Add try-catch-finally to unit tests.

2020-11-09 18:34 UTC, tatunka approved these changes

2020-11-11 22:06 UTC, aguentchev approved these changes

2020-11-11 22:06 UTC, merged