Alter king moves
tatunka/cs414-f20-TeamWeThemBoys pull request #22
Opened 2020-11-09 20:10 UTC by Jesse-Schmidt

2020-11-09 21:18 UTC, tatunka commented on xGame/Java/xgame/src/main/java/com/xgame/service/engine/ChessBoard.java
> +	public ArrayList<String> adjustPawnMoves(ArrayList<String> moves, Color threatColor, char c, char i){
I'm just thinking about a more clear name here. Like "findThreateningPawnMoves" or "findPawnAttackMoves" or something.

2020-11-10 20:44 UTC, tatunka commented on xGame/Java/xgame/src/main/java/com/xgame/service/engine/King.java
> +							&& !board.isThreatened(move, (color == Color.WHITE) ? Color.BLACK : Color.WHITE)){
this produces a bug in certain cases when the board is determining if the king is in check.

2020-11-10 20:45 UTC, tatunka commented on xGame/Java/xgame/src/test/java/com/xgame/engine/ChessBoardTest.java
> +//		assertTrue(board.isInCheck(Color.WHITE));
This revealed a bug in the code. Fix so that the test will pass.

2020-11-10 20:46 UTC, tatunka requested changes
Small bug under certain cases that needs fixing. Some minor refactoring necessary. Other than that, looks good.

2020-11-17 21:05 UTC, aguentchev approved these changes

2020-11-18 17:41 UTC, wstnmssr approved these changes

2020-11-18 19:20 UTC, merged