Deny draw
tatunka/cs414-f20-TeamWeThemBoys pull request #30
Opened 2020-11-20 21:14 UTC by wstnmssr

-If a player has suggested a draw, the other can deny that draw. the match will remain in progress

2020-11-20 21:49 UTC, aguentchev approved these changes

2020-11-23 00:13 UTC, tatunka commented on xGame/Java/xgame/src/main/java/com/xgame/service/ChessMatchService.java
> +		}
move this to right after the `m.orElseThorw()` so you don't make extra calls to the database getting users.

2020-11-23 00:15 UTC, tatunka requested changes
One or two small things. Great work.

2020-11-23 00:17 UTC, tatunka commented on xGame/Java/xgame/src/main/java/com/xgame/service/ChessMatchService.java
> +	public MatchStatus denyDraw(int matchId, int playerId) {
Instead of returning a MatchStatus you can just return void. If the FE doesn't get an error back, they know they deny succeeded.

2020-11-23 00:18 UTC, tatunka commented on xGame/Java/xgame/src/main/java/com/xgame/service/ChessMatchService.java
> +		messageRepo.save(new Message(opponent.get(), player.getNickname() + " has denied to the draw. Match " + matchId + " is still going!"));
"has denied the draw."

2020-11-23 17:19 UTC, tatunka approved these changes

2020-11-23 17:20 UTC, merged