Match selection
tatunka/cs414-f20-TeamWeThemBoys pull request #41
Opened 2020-12-04 15:43 UTC by aguentchev

Adds react views for match selection

2020-12-04 15:45 UTC, wstnmssr approved these changes

2020-12-04 16:50 UTC, lancemcmuffin requested changes
I'm getting this error upon logging in: 
![image](https://user-images.githubusercontent.com/22861808/101190759-138b2a80-3616-11eb-8439-1af5b77230e2.png)

2020-12-04 17:38 UTC, lancemcmuffin requested changes

2020-12-04 17:38 UTC, lancemcmuffin commented on xGame/client/src/Components/MatchSelect/MatchSelect.js
> +              {matchList?.map((X) => {
matchList occasionally gets set to false, so you need to check for that here by just adding "matchList &&" like so:
`{matchList && matchList?.map((X) => {`

2020-12-05 04:43 UTC, lancemcmuffin approved these changes

2020-12-05 04:44 UTC, merged